:description: Exception safety
:keywords: c++
:stylesheet: readthedocs.css
:source-highlighter: pygments

I was reading up about exception safe code in C++ and the difference between
the strong and basic exception guarantees. The article here
(http://www.gotw.ca/gotw/082.htm) outlines what it means for code to satisfy the
basic exception safety guarantee, however it doesn't give an example. So I came
up with something that is exception unsafe. The code below doesn't satisfy the
basic guarantee because it fails to delete the memory allocated to the pointer.

.Exception unsafe.
[source,cpp]
---------------------------------------
include::basic_excp_safety_violated.cpp[]
---------------------------------------

To ensure that it meets the basic guarantee the exception needs to be caught in
+g()+ and the memory deallocated. The code below does this.  Unfortunately there
is a bit of awkwardness here: note the double delete. One is in the 'bad' path
where the exception is caught and the other is in the 'good' code path. It would
be nice if the double delete wasn't necessary. Other languages have a +finally+
statement that is executed in both the 'good' and 'bad' case, however C\++
doesn't have this but the problem is still solvable as shown below.

.Basic exception safety met.
[source,cpp]
---------------------------------------
include::safe.cpp[]
---------------------------------------

The lack of a +finally+ statement in C\++ isn't a problem as long as the
principle *Resource Acquisition is Initialization* is applied. It's fairly
straightforward and with a little bit of thought I think that most good
programmers would realize what to do here in order to avoid having a double
delete. The trick is to write a wrapper class to manage the resource and in the
destructor clean up any allocated memory.  If you follow this guideline then
there is no need for C\++ to have a +finally+ statement.  This is mentioned in
the the C\++ FAQ in
link:http://www.parashift.com/c++-faq-lite/exceptions.html#faq-17.6[section
17.6]. The following code applies RAII. I've found myself doing this in code
I've writted without explicitly realizing the technique I was applying had a
name assoiciated with it.

.Basic exception safety with RAII.
[source,cpp]
-------------------------------------
include::raii_safe.cpp[]
-------------------------------------

